buildbot

diff --git a/.github/workflows/builbot.yml b/.github/workflows/builbot.yml
--- a/.github/workflows/builbot.yml
+++ b/.github/workflows/builbot.yml
@@ -17,15 +17,13 @@ jobs:
         shell: bash
         run: |
           #set -x
+          set -o pipefail
           # random selection of the swiftpackageindex repositories
           for REPO in $(curl https://raw.githubusercontent.com/SwiftPackageIndex/PackageList/refs/heads/main/packages.json | jq -r '.[]' | sort -R | head -n 10) ; do
             DIR=$(echo "${REPO}" | cut -f 4- -d '/' | sed 's;.git$;;g')
             echo "Building repository: ${DIR} (https://swiftpackageindex.com/${DIR})"
 
-            mkdir -p ${DIR}
-            cd ${DIR}
-            ls -la
-            (git clone ${REPO} . && ${{ steps.setup-toolchain.outputs.swift-build }} -c debug) > buildlog.txt && echo "SUCCESS: ${REPO}" || echo "FAILED: ${REPO}"
+            (git clone "${REPO}" "${DIR}" && ${{ steps.setup-toolchain.outputs.swift-build }} -c debug --package-path "${DIR}") | tee "${DIR}"/buildlog.txt && echo "SUCCESS: ${REPO}" || echo "FAILED: ${REPO}"
             cd -
             #exit 0
           done
